name: 'RepoDynamics PyTests'
description: 'Test Python packages'
author: 'Armin Ariamajd'
branding:
  icon: file-text
  color: blue


inputs:

  repository:
    description: Repository to checkout, i.e. the `repository` input of `actions/checkout`.
    default: ${{ github.repository }}
    required: false

  ref:
    description: |
      Reference to checkout, i.e. the `ref` input of `actions/checkout`.
    default: ""
    required: false

  python-version:
    description: Python version to use.
    default: '3.x'
    required: false

  package-source:
    description: |
      Source to install the package; options: 'GitHub', 'TestPyPI', 'PyPI'.
    default: local
    required: false

  package-name:
    description: |
      Name of the package to install, when `install_source` is 'testpypi' or 'pypi'.
    default: ""
    required: false

  package-version:
    description: |
      Version of the package to install, when `install_source` is 'testpypi' or 'pypi'.
    default: ""
    required: false

  path-root:
    description: |
      Path to the root directory.
    default: .
    required: false

  path-config:
    description: |
      Path to the configuration file.
    default: pyproject.toml
    required: false

  path-tests:
    description: |
      Path to the tests directory.
    default: ./tests
    required: false

  path-local:
    description: |
      Path to the local directory.
    default: ./.local
    required: false

  max-retries:
    description: |
      Maximum number of retries.
    default: '15'
    required: false

  retry-delay:
    description: |
      Delay between retries in seconds.
    default: '60'
    required: false


runs:
  using: "composite"
  steps:

    - name: 'Initialize'
      shell: bash
      run: |
        # Initialize
        printf "\n\n$(cat ${{github.action_path}}/logo.txt)\n\n\n"
        echo -e "\033[1;30;48;2;0;162;255m Initialize "

#    - if: ${{ inputs.package-source == 'GitHub' }}
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0
#    - if: ${{ inputs.package-source != 'GitHub' }}
#      uses: actions/checkout@v3
#      with:
#        repository: ${{ inputs.repository }}
#        ref: ${{ inputs.ref }}
#        sparse-checkout-cone-mode: false
#        sparse-checkout: |
#          ${{ inputs.path-local }}
#          ${{ inputs.path-tests }}
#          ${{ inputs.path-config }}
#          requirements.txt

    - name: 'Set up Python'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: 'Install package'
      shell: bash
      run: |
        # Setup Environment
        source $(echo "${{ github.action_path }}" | sed 's/\\/\//g')/retry.sh
        
        echo "::group::Update pip"
        python -m pip install --upgrade pip
        echo "::endgroup::"
        
        echo "::group::Install Package"
        if [ "${{inputs.package-source}}" = "GitHub" ]; then
            python -m pip install .
        
        elif [ "${{ inputs.package-source }}" = "TestPyPI" ]; then
            python -m pip install -r requirements.txt

            COMMAND="python -m pip install \
              ${{ inputs.package-name }}==${{ inputs.package-version }} \
              --no-deps \
              --index-url https://test.pypi.org/simple/"
            retry_command "$COMMAND" "${{ inputs.max-retries }}" "${{ inputs.retry-delay }}"
        
        elif [ "${{inputs.package-source}}" = "PyPI" ]; then
            if [ -z "${{ inputs.package-version }}" ]; then
                COMMAND="python -m pip install ${{ inputs.package-name }}"
            else
                COMMAND="python -m pip install ${{ inputs.package-name }}==${{ inputs.package-version }}"
            fi
            retry_command "$COMMAND" "${{ inputs.max-retries }}" "${{ inputs.retry-delay }}"

        else
            echo "Invalid package-source: '${{ inputs.package-source }}'."
            exit 1
        fi
        echo "::endgroup::"
        
        echo "::group::Install Test-Suite"
        python -m pip install ${{ inputs.path-tests }}
        echo "::endgroup::"

    - name: 'Display info'
      shell: bash
      run: |
        echo "::group::Python version"
        python -c "import sys; print(sys.version)"
        echo "::endgroup::"
        echo "::group::pip list"
        python -m pip list
        echo "::endgroup::"
        echo "::group::OS and hardware info"
        uname -a
        echo "::endgroup::"
        echo "::group::Disk space usage"
        df -h
        echo "::endgroup::"
        echo "::group::Available system resources"
        ulimit -a
        echo "::endgroup::"
        echo "::group::Root directory"
        ls -a
        echo "::endgroup::"
        echo "::group::File tree"
        find .
        echo "::endgroup::"
    
    - name: 'Test import package'
      shell: python
      run: |
        import ${{ inputs.package-name }} as pkg
        print(pkg.__version__)

#    - name: 'Run dependency tests'
#      shell: bash
#      run: pipreqs ./src --debug --print

    - name: 'Run unit tests'
      shell: bash
      run: python -m ${{ inputs.package-name }}_tests

    - name: 'Upload coverage reports to codecov'
      if: ${{ !cancelled() && inputs.package-source == 'GitHub' }}
      # https://github.com/marketplace/actions/codecov
      # https://github.com/codecov/codecov-action
      uses: codecov/codecov-action@v3
      with:
        directory: ${{ inputs.path-local }}/report/pytest_cov
        fail_ci_if_error: false
        verbose: true
        env_vars: OS,PYTHON

